version: "3.2"

services:
  api:
    build:
      context: .docker
    container_name: api
    volumes:
      - .:/var/www/html
    ports:
      - 8000:9000
    restart: always
    entrypoint: sh /var/www/html/.docker/entrypoint.sh
    depends_on:
      - database

  database:
    image: postgres
    container_name: db_api
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}